spring:
  datasource:
    username: admin-prod
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    url: jdbc:postgresql://localhost:2345/companies-prod
    password: admin-prod
